#!/usr/bin/env python
import os
import sys
import cgi

def application(environ, start_response):
	ctype = 'text/plain'
	if environ['PATH_INFO'] == '/health':
		response_body = "1"
		status = '200 OK'
	elif environ['PATH_INFO'] == '/env':
		response_body = ['%s: %s' % (key, value)
                    for key, value in sorted(environ.items())]
		response_body = '\n'.join(response_body)		
		status = '200 OK'
	else:
		try:
			form = cgi.FieldStorage( fp=environ['wsgi.input'],environ=environ,keep_blank_values=True)

		except:
			response_body = "Black hole created."			
			status = '500 Internal Server Error'
		
		
		try:
			fileitem = form['datei']
			fn = os.path.basename(fileitem.filename)
			replayfile = fileitem.file
			
			import sc2reader
			from sc2reader.scripts.sc2json import toJSON
			configuredToJSON = toJSON(indent=2)
			replay = sc2reader.load_replay(replayfile)
			
			ctype = 'text/json'
			response_body = configuredToJSON(replay)
			status = '200 OK'
		except KeyError:
			response_body = "File not provided"			
			status = '500 Internal Server Error'
		except:
			e = sys.exc_info()[0]
			response_body = "Error: %s" % e			
			status = '500 Internal Server Error'

	response_headers = [('Content-Type', ctype), ('Content-Length', str(len(response_body)))]
	#
	start_response(status, response_headers)
	return [response_body.encode('utf-8') ]

#
# Below for testing only
#
if __name__ == '__main__':
	from wsgiref.simple_server import make_server
	httpd = make_server('localhost', 8051, application)
	# Wait for a single request, serve it and quit.
	httpd.handle_request()
