#!/usr/bin/env python
import os
import sys
import cgi

def application(environ, start_response):
	ctype = 'text/plain'
	if environ['PATH_INFO'] == '/health':
		response_body = "1"
	elif environ['PATH_INFO'] == '/env':
		response_body = ['%s: %s' % (key, value)
                    for key, value in sorted(environ.items())]
		response_body = '\n'.join(response_body)
	else:
		try:
			#fileitem = cgi.FieldStorage()
			#if 'datei' in form:
			#	#fn = os.path.basename(fileitem.filename) 
			#	# open('uploads/' + fn, 'wb').write(fileitem.file.read())
			#	#fileitem.file.read())
			#else:
			#	replayfile = "1.SC2Replay"
		
			import sc2reader
			from sc2reader.scripts.sc2json import toJSON
			configuredToJSON = toJSON(indent=2)
			replay = sc2reader.load_replay("1.SC2Replay")
		
			ctype = 'text/json'
			response_body = configuredToJSON(replay)
		except:
			e = sys.exc_info()[0]
			response_body = "Error: %s" % e

	status = '200 OK'
	response_headers = [('Content-Type', ctype), ('Content-Length', str(len(response_body)))]
	#
	start_response(status, response_headers)
	return [response_body.encode('utf-8') ]

#
# Below for testing only
#
if __name__ == '__main__':
	from wsgiref.simple_server import make_server
	httpd = make_server('localhost', 8051, application)
	# Wait for a single request, serve it and quit.
	httpd.handle_request()
